### ISSUE TITLE
nsenter: failed to parse pid: '-p'

### ISSUE THREAD

**Issue by Panke** [nix-community/NixOS-WSL#87] opened 2022-04-27 10:23 UTC
## Bug description
I installed it but I cannot start it, because `nsenter: failed to parse pid: '-p'.

## To Reproduce
1. Get the installer and follow readme instructions (see terminal output below)

Include relevant console logs

```
PS C:\Users\bcr88\Downloads> wsl --import NixOS ..\NixOS\ .\nixos-wsl-installer.tar.gz --version 2
PS C:\Users\bcr88\Downloads> wsl -d NixOS
Unpacking root file system...
 184MiB 0:00:07 [24.6MiB/s] [=================================================================================================================================================================>] 100%
Activating nix configuration...
Copying /usr/share/applications
Copying /usr/share/icons
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Cleaning up installer files...
finding garbage collector roots...
removing stale link from '/nix/var/nix/gcroots/auto/6yfbrv8wfkyl40wq6827lamr9m29z7wg' to '/build/nix/var/nix/profiles/per-user/root/channels-1-link'
removing stale link from '/nix/var/nix/gcroots/auto/zxi8v969la5n36bg7gs016wgcif4qjhp' to '/build/nix/var/nix/profiles/system-1-link'
deleting garbage...
deleting '/nix/store/svw89j47vr3h792f75nfgh5x9s48rn0w-pv-1.6.20'
deleting '/nix/store/m0qmllywgy9wl4ia7vvpz7p53kzxv681-busybox-1.34.1'
deleting '/nix/store/m7cghw288wks5s5mkxpg1k3h5ivlg1ch-installer.sh'
deleting '/nix/store/8hm7r6m8y0fjrb4qjv8gs1ba04g51166-tarball'
deleting '/nix/store/y608sw04xdqhha69raxpj2rsk007n7wf-wsl-prepare'
deleting '/nix/store/4ryxif8fmjb362ry8ylx29hsxp0zgpax-source'
deleting unused links...
note: currently hard linking saves -0.00 MiB
6 store paths deleted, 185.42 MiB freed
5.05 MiB freed by hard-linking 3499 files
Starting systemd...
PS C:\Users\bcr88\Downloads> wsl -d NixOS
nsenter: failed to parse pid: '-p'
```

ec7667a682ac2a796774d9357210438359c1f19df8755fb72ed730305612e29a  nixos-wsl-installer.tar.gz

**Comment by sielicki** [comment] 2022-04-27 16:24
Duplicate of https://github.com/nix-community/NixOS-WSL/issues/67

Please try the `-fixed` installer.

**Comment by Panke** [comment] 2022-04-27 16:26
Ah sorry, I only looked at the open bugs.

**Comment by sielicki** [comment] 2022-04-27 16:27
@nzbr is it possible to delete the old tarball on the release page?

**Comment by nzbr** [comment] 2022-04-27 16:36
I can't force-push the tag, unfortunately. It stopped working a while ago. @Mic92 ist that on purpose? Or is something broken on my end?

**Comment by Panke** [comment] 2022-04-28 18:52
Works with the newer release!

**Closed** 2022-06-01 06:07 UTC
Labels: bug

**Comment by dliberalesso** [comment] 2022-08-22 14:51
I'm experiencing the same problem with the installer from release 22.05-5c211b47

**Comment by RivenSkaye** [comment] 2022-08-25 07:21
Commenting here because this is resurfacing for me when installing the latest release. The entire unpacking step works perfectly fine, but then it just sits there, claiming to start systemd but never actually carrying on. SIGKILL is required to continue (I let it sit for well over 20 mins). Afterwards, any attempt to start `wsl -d NixOS` results in the same error.

<details>
    <summary>Log of the install attempt, click to expand</summary>

```cmd
> wsl -d NixOS
Unpacking root file system...
 307MiB 0:00:17 [18.0MiB/s] [=========================================================================================>] 100%
Activating nix configuration...
Copying /usr/share/applications
Copying /usr/share/icons
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
setting up /bin...
Cleaning up installer files...
finding garbage collector roots...
removing stale link from '/nix/var/nix/gcroots/auto/6yfbrv8wfkyl40wq6827lamr9m29z7wg' to '/build/nix/var/nix/profiles/per-user/root/channels-1-link'
removing stale link from '/nix/var/nix/gcroots/auto/zxi8v969la5n36bg7gs016wgcif4qjhp' to '/build/nix/var/nix/profiles/system-1-link'
deleting garbage...
deleting '/nix/store/ab5mixyq1zg0x5lnr5i7m4l5815fp1h8-wsl-prepare'
deleting '/nix/store/scr6balqjknqpgm7igd0b4pagmp2ldbl-installer.sh'
deleting '/nix/store/pmb55f6rk98cdycqf589vb3xpbg15k28-source'
deleting '/nix/store/cq6l0b0iv2y3gln3xi6nzxs57mz5rxws-tarball'
deleting '/nix/store/0p9v7yvblgxsds9pbsrir3af6gw0x77s-busybox-1.35.0'
deleting '/nix/store/5mism3qrfc3ah9ahvf7sczxy4bax9cgq-pv-1.6.20'
deleting unused links...
note: currently hard linking saves -0.00 MiB
6 store paths deleted, 309.05 MiB freed
Optimizing store...
5.74 MiB freed by hard-linking 3714 files
Starting systemd...
```

At this point, `ctrl`+`C` is the _only_ way to continue. The shell hangs on this, presumably because of the following:

```cmd
> wsl -d NixOS
nsenter: failed to parse pid: '-p'
```

In the meantime I'll try installing the previous (-fixed) release and upgrading from there to see if it helps

</details>

**Comment by nzbr** [comment] 2022-09-08 21:55
@RivenSkaye Did you manage to get it to work? If not, can you try [the latest build](https://github.com/nix-community/NixOS-WSL/actions/runs/2948166873)? (the installer tarball is inside the "installer" artifact, so you'll need to unpack that first)

**Comment by dliberalesso** [comment] 2022-09-09 21:14
@RivenSkaye You can install direclty via the [tarball available in the latest build](https://github.com/nix-community/NixOS-WSL/releases/download/22.05-5c211b47/nixos-wsl-x86_64-linux.tar.gz) using the command `wsl --import NixOS .\NixOS\ nixos-wsl-x86_64-linux.tar.gz --version 2`.

**Comment by nzbr** [comment] 2022-09-10 21:54
@dliberalesso The link I shared doesn't go to the latest release, but the latest CI run of the main branch, which is a few commits ahead and contains a full rewrite of syschdemd (the systemd wrapper script)

**Comment by dliberalesso** [comment] 2022-09-10 22:28
@nzbr In that case, I'll try it too. Thanks!

**Comment by jamesreprise** [comment] 2022-09-22 20:08
I also had the exact same issue as @RivenSkaye and @nzbr's fix worked perfectly (thank you!) It might be worth re-opening this issue so that it's visible to anyone else having the same problem without removing `issue:open`.

**Comment by nzbr** [comment] 2022-09-23 02:46
I have left the issue closed (as it seems to be fixed on main), but pinned it so that anyone experiencing that problem can find it on top of the issue list
