### ISSUE TITLE
How-To Doc

### ISSUE THREAD

**Issue by JasonGoemaat** [nix-community/NixOS-WSL#441] opened 2024-03-20 18:47 UTC
Very new to Nix, love this repository but had a hard time figuring out how to just add packages to the global `configuration.nix`.  I saw there was a space for a howto doc that wasn't created so I decided to add some examples.

**Comment by 0xLunch** [comment] 2024-04-08 00:53
You'll want to do a bunch of googling on different setups since there are multiple ways to get your programs installed. I'll give a quick rundown here but this is more a question for Nix communities directly and not specific to NixOS-WSL.

For global system-wide packages that will exist for every user, every system, etc you can use `environment.systemPackages` inside your `etc/nixos/configuration.nix` file
example:
```nix
  # System Packages
  environment.systemPackages = with pkgs; [
    zsh
    wget
    htop
    tmux
  ];
```

When you `sudo nixos-rebuild switch` these will be included systemwide.

Another way is to simply enable a program that's in nixpkgs, ie: `programs.zsh.enable = true`. This can be done in your general configuration, or more preferably within your `home-manager` config so it applies to your specific user and not the entire system.

Hope this points you in the right direction.

**Comment by nzbr** [comment] 2024-10-13 22:03
This is basically a duplicate of the PR, so I'm closing this issue

**Closed by nzbr** 2024-10-13 22:03 UTC
Labels: documentation, duplicate
