### ISSUE TITLE
 fchmod() of /tmp/.X11-unix failed: Read-only file system

### ISSUE THREAD

**Issue by trayanr** [nix-community/NixOS-WSL#269] opened 2023-07-24 09:00 UTC
## Bug description

When running `sudo nixos-rebuild switch` I get an error: `fchmod() of /tmp/.X11-unix failed: Read-only file system`
## To Reproduce
install `nixos-wsl-x86_64-linux.tar.gz`. change the configuration.nix to contain also an ```environment.systemPackages = with pkgs; [
    vim
  ];```
**Expected behavior**

To actually rebuild the system.
## Logs
```
building Nix...
building the system configuration...
activating the configuration...
Copying /usr/share/applications
Copying /usr/share/icons
setting up /etc...
setting up /bin...
reloading user units for nixos...
setting up tmpfiles
fchmod() of /tmp/.X11-unix failed: Read-only file system
warning: error(s) occurred while switching to the new configuration
```
Additional info: even if I run chmod 1777 to this folder nothing happens. Perhaps the systemPackages have to be somewhere else? Very new to flakes, so I am not sure.

sha256 `4776aa5115edb422763736f63eb9452479c4214d33f46c3b26659c77963ced25`

**Comment by SuperSandro2000** [comment] 2023-07-24 09:16
> Additional info: even if I run chmod 1777 to this folder nothing happens. Perhaps the systemPackages have to be somewhere else? Very new to flakes, so I am not sure.

That isn't relevant for this problem.

Are you running the latest WSL? Can you run ``wsl update``?

**Comment by trayanr** [comment] 2023-07-24 09:29
`wsl --update`: 
```
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

**Comment by nzbr** [comment] 2023-07-24 20:36
I suspect this might be related to the latest WSL update. I'll see if I can reproduce it

**Comment by nzbr** [comment] 2023-07-24 20:56
I'm not able to reproduce it right now (on main with the latest WSL release). What does `nixos-wsl-version` report for you?

**Comment by trayanr** [comment] 2023-07-25 07:34
I don't have this command neither in wsl-nixos nor windows. `nixos-version` : `22.05.20220812.5c211b4 (Quokka)` and `wsl --version` : 
```
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3208
```

**Comment by SuperSandro2000** [comment] 2023-07-25 09:52
Please update your Nixos-wsl, the command is included since multiple months.

**Comment by trayanr** [comment] 2023-07-26 09:32
I have uninstalled the old NixOS with `wsl --unregister`. Then I downloaded the latest release from [here](https://github.com/nix-community/NixOS-WSL/releases/tag/22.05-5c211b47). Downloaded `nixos-wsl-x86_64-linux.tar.gz`, because the installer hangs at starting systemd. The nixos-wsl-version command is still missing. This is the release that is the latest, but it was released ~ 11 months ago on August 2022. If this command was released couple months ago, and the release is older, how can I get it? Could it be that the x86_64 has missing commands, do I have to package the release myself or is there a way to update from the git repository? Something to note is that it actually installs the packages when I run `sudo nixos-rebuild switch`. Vim has been installed, just this error appears, but it may be more of a warning. How do I update my Nixos-wsl?

**Comment by SuperSandro2000** [comment] 2023-07-26 22:58
From the latest action run https://github.com/nix-community/NixOS-WSL/actions/workflows/main.yml https://github.com/nix-community/NixOS-WSL/actions/runs/5657306903?pr=263

**Comment by dantefromhell** [comment] 2023-07-27 23:20
I'm having the same issue.

I installed from the latest github [installer release](https://github.com/nix-community/NixOS-WSL/releases/download/22.05-5c211b47/nixos-wsl-installer.tar.gz) using `wsl --import` on the newest release of WSL according to `wsl --update` under Windows 10.

The folder `/tmp/.X11-unix` is a read-only mounted `tmpfs`:

```
$ mount | grep 'X11'
none on /tmp/.X11-unix type tmpfs (ro,relatime)
```



> Please update your Nixos-wsl

I was able to update based with slightly modified instructions from https://github.com/nix-community/NixOS-WSL/releases/tag/22.05-5c211b47
1. Replacing `/etc/nixos/nixos-wsl` with commit [01112ba](https://github.com/nix-community/NixOS-WSL/commit/01112baf546b5577038e2a422a5215eedd9bc84b) by downloading the zip archive.
2. updating the `nixos` channel to `https://nixos.org/channels/nixos-23.05`


Only updating `/etc/nixos/nixos-wsl` resulted in the following error while running `nixos-rebuild switch`
```
error: The option 'boot.kernel.enable' does not exist'
```

BTW, the `nixos-rebuild switch` took quite long, as it was building `wayland-protocols` and `mesa` from source.

> What does `nixos-wsl-version` report for you?

Before the upgrade it was non-existent, after the upgrade
```
NixOS-WSL DEV_BUILD dirty syschdemd
```

**Comment by SuperSandro2000** [comment] 2023-07-28 09:47
> I was able to update based with slightly modified instructions from [`22.05-5c211b47` (release)](https://github.com/nix-community/NixOS-WSL/releases/tag/22.05-5c211b47)
> 
> 1. Replacing `/etc/nixos/nixos-wsl` with commit [01112ba](https://github.com/nix-community/NixOS-WSL/commit/01112baf546b5577038e2a422a5215eedd9bc84b) by downloading the zip archive.
> 2. updating the `nixos` channel to `https://nixos.org/channels/nixos-23.05`

Please just use flakes which make this process super easy and simple.

**Comment by dantefromhell** [comment] 2023-07-28 21:02
> Did you run nix-channel --update? That option does exist in 23.05 but not 22.11 IIRC

Yes I updated the channel while switching to `23.05`.

The current release image has the `nixos` channel set to `22.05` right? 
From what I understand updating this channel would not have resolved the `boot.kernel.enable missing` error, correct?


> Please just use flakes which make this process super easy and simple.

Agreed, my next step is to create a flake that has `nixpkgs` and `nixos-wsl` as inputs and wraps `configuration.nix`.

I wonder, could this flake be added to `/etc/nixos`? If it wraps the existing `configuration.nix` file, it shouldn't impose flakes on people that prefer to not use them, correct?

**Comment by nzbr** [comment] 2023-08-08 23:32
> From what I understand updating this channel would not have resolved the boot.kernel.enable missing error, correct?

Correct

You need to update the channel and the module at the same time. The `boot.kernel.enable` option was added after 22.05 so it's not present there and updating the old channel can't help with that

We can't add a flake to `/etc/nixos` by default, because `nixos-rebuild` would use that so it'd break channels for everyone using them

**Comment by zybzzc** [comment] 2023-08-19 19:36
@dantefromhell 
Can you elaborate on your resolution process?

I did the following steps and it still show the error:
1. Download [01112ba](https://github.com/nix-community/NixOS-WSL/commit/01112baf546b5577038e2a422a5215eedd9bc84b) zip archive and copy to `/etc/nixos/nixos-wsl` in wsl.
2. Run follow commands in wsl:
```
nix-channel --add https://mirrors.ustc.edu.cn/nix-channels/nixos-23.05 nixos
nix-channel --update
```

**Comment by dantefromhell** [comment] 2023-08-20 02:10
@zybzzc It could be possible that I forgot to document a step, or overlooked to document something important. Right now I don't have the time to re-do and check my work.

Personally I am waiting for the next release as tracked in #271

**Comment by zybzzc** [comment] 2023-08-21 07:40
@dantefromhell 
Thanks, I'll wait for the next release too then.I'm a newbie just in time to dive into nix and flake.

**Comment by K900** [comment] 2023-09-30 05:45
Should be fixed upstream now.

**Closed by K900** 2023-09-30 05:45 UTC
Labels: bug
