### ISSUE TITLE
Activating native systemd support breaks shell

### ISSUE THREAD

**Issue by aikooo7** [nix-community/NixOS-WSL#486] opened 2024-06-07 19:16 UTC
## Bug description

When enabling native systemd support and rebuild, switch and restart system you will be unable to log in to your system unless you use the recovery shell or use the shell binary directly instead of the wrapper.

Note: While trying to find what was the cause of the issue I rebuilt my home-manager and got ``Failed to connect to bus: No such file or directory`` so maybe #375 is related.

## To Reproduce
Add ``wsl.nativeSystemd = true;``
Run ``sudo nixos-rebuild switch``
Run ``wsl --shutdown`` in cmd.
Run ``wsl -d NixOS`` in cmd. NixOS should be your nixos distro's name in wsl.

## Logs
```
thread 'main' panicked at src/shell_wrapper.rs:105:10:
called `Result::unwrap()` on an `Err` value: When initializing journal logger

Caused by:
    No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## WSL version

2.0.9.0
```
WSL version: 2.0.9.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.4170
```

**Comment by nzbr** [comment] 2024-06-15 16:50
It looks like systemd hasn't started properly. That should obviously not crash the shell though, I'll fix that

**Comment by nzbr** [comment] 2024-06-15 16:51
As for the underlying problem: Can you send me the output of `dmesg` executed in another distro right after this happens. To reduce the size of the output, it probably makes sense to shut down WSL with `wsl --shutdown` before that

**Comment by polybluez** [comment] 2024-08-13 18:07
Is this the same error?

```
C:\Users\Admin>wsl
when trying to exec the wrapped shell

Caused by:
    No such file or directory (os error 2)
```

**Comment by polybluez** [comment] 2024-08-14 17:22
There is a workaround: first fire up WSL with a recovery shell `wsl -d NixOS --system --user root -- /mnt/wslg/distro/bin/nixos-wsl-recovery` and then enter WSL as usual

**Comment by nzbr** [comment] 2024-08-18 17:15
@polybluez no, that is a diffferent error. I suspect that the one @aikooo7 experienced was a race condition, because the shell wrapper tried to connect to journald before that was started. That one should be fixed now, because it does not result in a crash anymore. Your error looks like the wrapper tries to start your shell, but the shell's binary just does not exist for some reason. The same probably would have happened without the wrapper

**Comment by leonbreedt** [comment] 2024-09-12 22:39
This occurs for me as well, I basically have to revert to `wsl.nativeSystemd = false;` , or I cannot use NixOS-WSL.

Data point: My NixOS-WSL is built using a flake, using a user created by the flake (and not the `nixos` user).

**Comment by nzbr** [comment] 2024-10-13 21:48
@leonbreedt The latest tarball ships with native systemd enabled, so if that is working for you it being enabled isn't the actual problem. I suspect there's something in your config that interferes with it. Please open a new issue if you still have that problem.

@aikooo7 Because the race-condition should be fixed and I didn't hear from you after that, I'm going to close this for now. Feel free to re-open if the issue is still present

**Closed by nzbr** 2024-10-13 21:48 UTC
Labels: bug

**Comment by leonbreedt** [comment] 2024-10-14 20:50
@nzbr: after i updated to latest nixpkgs, the issue no longer happens. thanks for the ping!
