### ISSUE TITLE
Can't enter FHS environment with /tmp/.X11-unix soft linked to /mnt/wslg/.X11-unix

### ISSUE THREAD

**Issue by ATL-AGraffeo** [nix-community/NixOS-WSL#328] opened 2023-11-08 20:04 UTC
The default behavior of NixOS-WSL seems to have /tmp/.X11-unix soft linked to /mnt/wslg/.X11-unix.  However, when starting any environment built by pkgs.buildFHSUserEnv (ex: steam-run), I get the error:

`bwrap: Can't mount tmpfs on /newroot/tmp/.X11-unix: No such file or directory`

This can be fixed by either directly copying /mnt/wslg/.X11-unix over to /tmp/.X11-unix, or by deleting /tmp/.X11-unix entirely and letting it be created by buildFHSUserEnv, but hopefully this can be patched to provide expected behavior out-of-the-box.

NixOS version: 23.05.4621.017ef2132a5b
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134

**Comment by SuperSandro2000** [comment] 2023-11-09 00:54
There should be a [symlink created](https://github.com/nix-community/NixOS-WSL/blob/6e3d83b05ea7fe090a406081db871c8090a00fba/modules/systemd/default.nix#L43) but I think the new syntax only works for WSL 2.0.0 and onwards.

**Comment by ATL-AGraffeo** [comment] 2023-12-06 15:41
> There should be a [symlink created](https://github.com/nix-community/NixOS-WSL/blob/6e3d83b05ea7fe090a406081db871c8090a00fba/modules/systemd/default.nix#L43) but I think the new syntax only works for WSL 2.0.0 and onwards.

Yes, that's my point.  It only appears to work if /tmp/.X11-unix is hard linked.  If it is symlinked to somewhere else, I get the error described above.

**Comment by SuperSandro2000** [comment] 2023-12-06 16:06
We only really support WSL 2.0 anymore, see https://github.com/nix-community/NixOS-WSL#system-requirements

If you find a solution, please create a PR.

@nzbr do we want to close this?

**Comment by MetalJulia** [comment] 2023-12-06 21:01
This issue occurs for me with WSL2.

**Comment by nzbr** [comment] 2023-12-07 06:17
WSL2 ist (due to Microsofts unfortunate naming) not the same thing as WSL version 2.0.0. WSL2 refers to running WSL as a Hyper-V VM as opposed to through emulation (WSL1), whereas WSL 2.0.0 refers to the version of the WSL binaries, which handle both WSL1 and WSL2. You can check which version you have with `wsl --version`. If that flag does not exist for you, you probably need to install [the latest WSL version from the Microsoft Store](https://apps.microsoft.com/detail/9P9TQF7MRM4R)

**Comment by jonahbron** [comment] 2023-12-14 06:41
I'm encountering this issue as well, definitely on WSL version 2.  Microsoft store shows me as having the latest installed.

```
> wsl --version
WSL version: 2.0.9.0
```

Running `steam-run` gives me the same error:

```
$ steam-run node_modules/.bin/workerd
bwrap: Can't mount tmpfs on /newroot/tmp/.X11-unix: No such file or directory
```

**Comment by nzbr** [comment] 2024-01-06 00:05
I managed to reproduce it. It is in fact the symlink that is the issue here. If you run `sudo rm /tmp/.X11-unix`, steam-run starts working. But that will break GUI support instead, obviouslt

**Comment by aikooo7** [comment] 2024-02-11 18:51
Do we have any updates on this? @nzbr 

I'm getting this error since some time ago

**Closed** 2024-02-24 15:34 UTC
Labels: bug

**Comment by kumkee** [comment] 2024-03-03 07:58
> WSL2 ist (due to Microsofts unfortunate naming) not the same thing as WSL version 2.0.0. WSL2 refers to running WSL as a Hyper-V VM as opposed to through emulation (WSL1), whereas WSL 2.0.0 refers to the version of the WSL binaries, which handle both WSL1 and WSL2. You can check which version you have with `wsl --version`. If that flag does not exist for you, you probably need to install [the latest WSL version from the Microsoft Store](https://apps.microsoft.com/detail/9P9TQF7MRM4R)

The issue persists in WSL 2.0.9.0 (version from `wsl --version`) as many mentioned above. 

Please reopen the issue.

**Comment by SuperSandro2000** [comment] 2024-03-03 12:39
This is not an WSL issue itself and for fixed on master. Please update your flake inputs and retest.

**Comment by SuperSandro2000** [comment] 2024-03-03 12:39
This is not an WSL issue itself and for fixed on master. Please update your flake inputs and retest.
