### ISSUE TITLE
Fresh install: builder for `nixos-wsl-utils` fails

### ISSUE THREAD

**Issue by jchvz** [nix-community/NixOS-WSL#504] opened 2024-06-27 00:15 UTC
## Bug description
On a fresh install of NixOS on WSL 2, the "welcome" setup commands do not succeed.

## To Reproduce
- Download the latest release from [here](https://github.com/nix-community/NixOS-WSL/releases/tag/2311.5.3) (checksum `4bf8560df6950a295db481ba2917ac76b09b856abcd4eabe4842af39d482ec25`) and save to `nixos-wsl.tar.gz`
- From powershell, run `wsl --import NixOS .\NixOS\ nixos-wsl.tar.gz --version 2` and then `wsl -d NixOS`
- Follow the initial welcome instructions 

## Logs

```
Welcome to your new NixOS-WSL system!

Please run `sudo nix-channel --update` and `sudo nixos-rebuild switch` now, to ensure you're running the latest NixOS and NixOS-WSL versions.

If you run into issues, please report them on our Github page at https://github.com/nix-community/NixOS-WSL or come talk to us on Matrix at #wsl:nixos.org.

❄️ Enjoy NixOS-WSL! ❄️

Note: this message will disappear after you rebuild your system. If you want to see it again, run `nixos-wsl-welcome`.

[nixos@nixos:~]$ sudo nix-channel --update
this derivation will be built:
  /nix/store/i68n4pdgv66n2zfy2h8z1jkvcdmgbwxz-nixos-wsl.drv
building '/nix/store/i68n4pdgv66n2zfy2h8z1jkvcdmgbwxz-nixos-wsl.drv'...
unpacking channels...

[nixos@nixos:~]$ sudo nixos-rebuild switch
```
Many successful steps are printed, and then at the bottom, it continues:

```
Executing cargoBuildHook
++ env CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/cc CC_X86_64_UNKNOWN_LINUX_GNU=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/cc CXX_X86_64_UNKNOWN_LINUX_GNU=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/c++ CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/cc CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu HOST_CC=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/cc HOST_CXX=/nix/store/shdkxxdlpv66wl33rh9d01zfypaka1dn-gcc-wrapper-12.3.0/bin/c++ cargo build -j 16 --target x86_64-unknown-linux-gnu --frozen --profile release
error: package `clap_lex v0.7.0` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.73.0
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap_lex@0.7.0 --precise ver
where `ver` is the latest version of `clap_lex` supporting rustc 1.73.0
error: builder for '/nix/store/0kl4pq7hmrw8yf6ph5kbcdjg8a8wllm7-nixos-wsl-utils-1.0.0.drv' failed with exit code 101
error: 1 dependencies of derivation '/nix/store/i7x0cvs2qpwbx8750akila1q42q43v2z-nixos-system-nixos-23.11.7714.90bd1b26e237.drv' failed to build
```

The entire log output is available here, if other parts are relevant: [nixos wsl2 initial startup fail.txt](https://github.com/user-attachments/files/16005522/nixos.wsl2.initial.startup.fail.txt)

## WSL version

```
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.22631.3737
```

**Comment by SuperSandro2000** [comment] 2024-06-28 23:34
Dupe of #483

**Closed** 2024-06-28 23:34 UTC
Labels: bug
