### ISSUE TITLE
Systemd fails to start when cgroups v2 is enabled

### ISSUE THREAD

**Issue by dingdang66686** [nix-community/NixOS-WSL#76] opened 2022-04-08 05:12 UTC
#logs:
---
Processing fstab with mount -a failed.

Unpacking root file system...
 184MiB 0:00:06 [26.5MiB/s] [========================================================================>] 100%
Activating nix configuration...
Copying /usr/share/applications
Copying /usr/share/icons
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
setting up /etc...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Cleaning up installer files...
finding garbage collector roots...
removing stale link from '/nix/var/nix/gcroots/auto/zxi8v969la5n36bg7gs016wgcif4qjhp' to '/build/nix/var/nix/profiles/system-1-link'
removing stale link from '/nix/var/nix/gcroots/auto/6yfbrv8wfkyl40wq6827lamr9m29z7wg' to '/build/nix/var/nix/profiles/per-user/root/channels-1-link'
deleting garbage...
deleting '/nix/store/m0qmllywgy9wl4ia7vvpz7p53kzxv681-busybox-1.34.1'
deleting '/nix/store/3y5hdyv6n1dbkfg7x3nn59hzhpwj51bl-installer.sh'
deleting '/nix/store/svw89j47vr3h792f75nfgh5x9s48rn0w-pv-1.6.20'
deleting '/nix/store/4z8x8wq942jxghp1261lc5hajj7q3fx3-tarball'
deleting '/nix/store/pjsz3xk31a6w0z22n0yiir0cjz6w1lx1-wsl-prepare'
deleting '/nix/store/grqvhmymidyp0si0gga824jkwi4lfpjn-source'
deleting '/nix/store/trash'
deleting unused links...
note: currently hard linking saves -0.00 MiB
6 store paths deleted, 185.42 MiB freed
Optimizing store...
5.05 MiB freed by hard-linking 3499 files
Starting systemd...

**Comment by nzbr** [comment] 2022-04-08 05:28
Can you send me the sha256sum of your installer tarball, please?

**Comment by dingdang66686** [comment] 2022-04-08 05:54
stray@LAPTOP-QHKG7T54:/mnt/c/Users/stray/Downloads$ sha256sum nixos-wsl-installer-fixed.tar
d9e206817a77093341d4563605625b9dd7a783ad91f69f53f3ca3b3f3ac48df8  nixos-wsl-installer-fixed.tar

**Comment by dingdang66686** [comment] 2022-04-08 05:55
Sorry, I just closed it by accident.

**Comment by nzbr** [comment] 2022-04-08 06:06
I hadn't tried a gunzipped tarball before, but i'm not able to reproduce the issue right now (with identical hashes). Does the problem persist when you restart the WSL VM (`wsl --shutdown`)?

**Comment by dingdang66686** [comment] 2022-04-08 06:10
stuck on set up /etc.

# logs:
---
stray in ~\Downloads λ wsl --import NixOS D:\NixOS .\nixos-wsl-installer-fixed.tar
正在导入，这可能需要几分钟时间。
操作成功完成。
stray in ~\Downloads λ wsl -d NixOS
Processing fstab with mount -a failed.
...(same as above)
5.05 MiB freed by hard-linking 3499 files
Starting systemd...
^C
stray in ~\Downloads λ wsl --shutdown
stray in ~\Downloads λ wsl -d NixOS
Copying /usr/share/applications
Copying /usr/share/icons
setting up /etc...

**Comment by nzbr** [comment] 2022-04-08 06:16
Interesting, that is actually the same step as before (starting systemd; syschdemd does not have log output for that (yet))

**Comment by dingdang66686** [comment] 2022-04-08 06:23
I can go into the shell with `wsl -d nixos -e sh` but basic utils like ls, cat, vi is missing so I can't get any useful information from it

**Comment by nzbr** [comment] 2022-04-08 06:25
Try running `/nix/var/nix/profiles/system/activate` and `source /etc/set-environment`. That should make the nix environment available

**Comment by dingdang66686** [comment] 2022-04-08 06:34
Awesome! So how to start systemd manually then?

**Comment by nzbr** [comment] 2022-04-08 06:39
Systemd needs to run as PID 1, so the only way to properly start it is to run syschdemd.sh (the path is in /etc/passwd if you need it, but that does the same as opening a regular shell). Now that you are inside the nix environment, you should be able to get systemds logs using `journalctl`

**Comment by dingdang66686** [comment] 2022-04-08 06:45
systemd.pid exists but no corresponding process named systemd exists.

**Comment by dingdang66686** [comment] 2022-04-08 06:47
No journal files.

**Comment by nzbr** [comment] 2022-04-08 06:48
I tried on my (working) installation and did not get any journal entries outside of the namespace either...

**Comment by dingdang66686** [comment] 2022-04-08 06:49
Also, no systemd exists in my PATH.

**Comment by nzbr** [comment] 2022-04-08 06:51
That's not a problem. Systemd isn't in the path of most distros that use it, because it is executed as init

**Comment by dingdang66686** [comment] 2022-04-08 06:59
[root@nixos:/run/current-system/systemd/lib/systemd]# bash -x /nix/store/qml7bm85gcvfgn1gpryycbj6hrbnrapa-syschdemd/bin/
syschdemd
+ set -e
+ sw=/nix/var/nix/profiles/system/sw/bin
++ /nix/var/nix/profiles/system/sw/bin/readlink -f /nix/var/nix/profiles/system
+ systemPath=/nix/store/5sdc62vp6xn0zhxfxsljxw9fgn3f9amg-nixos-system-nixos-21.11.20220325.d89f18a
+ [[ 0 -ne 0 ]]
+ '[' '!' -e /run/current-system ']'
+ '[' '!' -e /run/systemd.pid ']'
+ start_systemd
+ /run/wrappers/bin/umount /proc/sys/fs/binfmt_misc
+ PATH=/run/current-system/systemd/lib/systemd:/nix/store/qif4jkzgrv09w9xyjvj4mn3sbz6829hw-e2fsprogs-1.46.5-bin/bin:/nix/store/irvl5f8z710fcxdkmrbasgy0qjv6iyrc-dosfstools-4.1/bin
+ LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive
+ /nix/store/d1v0v340rlvc36x3z4yvh7s04m8hlrj6-daemonize-1.7.8/bin/daemonize /run/current-system/sw/bin/unshare -fp --mount-proc /nix/store/5p3n24in6is3yzpvp7d29vzpbrh88fgb-systemd-wrapper.sh
+ /run/current-system/sw/bin/pgrep -xf systemd
+ status=1
+ [[ 1 -gt 0 ]]
+ /nix/var/nix/profiles/system/sw/bin/sleep 1
+ status=0
+ /nix/var/nix/profiles/system/sw/bin/nsenter -t 196 -p -m -- /nix/var/nix/profiles/system/sw/bin/systemctl is-system-running -q --wait
+ status=1
+ [[ 1 -gt 0 ]]
+ /nix/var/nix/profiles/system/sw/bin/sleep 1
+ status=0

**Comment by nzbr** [comment] 2022-04-08 07:04
Can you get into the namespace with `/nix/var/nix/profiles/system/sw/bin/nsenter -t 196 -p -m nix/var/nix/profiles/system/sw/bin/bash`?

**Comment by dingdang66686** [comment] 2022-04-08 07:05
Here I run the commands in my shell manually.
----
[root@nixos:~]# PATH=/run/current-system/systemd/lib/systemd:/nix/store/qif4jkzgrv09w9xyjvj4mn3sbz6829hw-e2fsprogs-1.46.5-bin/bin:/nix/store/irvl5f8z710fcxdkmrbasgy0qjv6iyrc-dosfstools-4.1/bin

[root@nixos:~]# LOCALE_ARCHIVE=/run/current-system/sw/lib/locale/locale-archive

[root@nixos:~]# /run/current-system/sw/bin/unshare -fp --mount-proc /nix/store/5p3n24in6is3yzpvp7d29vzpbrh88fgb-systemd-wrapper.sh
/nix/store/5p3n24in6is3yzpvp7d29vzpbrh88fgb-systemd-wrapper.sh: line 2: mount: command not found

[root@nixos:~]# mount
bash: mount: command not found

**Comment by dingdang66686** [comment] 2022-04-08 07:07
> Can you get into the namespace with `/nix/var/nix/profiles/system/sw/bin/nsenter -t 196 -p -m nix/var/nix/profiles/system/sw/bin/bash`?

What does 196 mean? The PID of something?

**Comment by nzbr** [comment] 2022-04-08 07:08
That is the systemd PID from outside the namespace

**Comment by dingdang66686** [comment] 2022-04-08 07:10
It seems that mount is not in the path.

> [root@nixos:~]# /run/current-system/sw/bin/unshare -fp --mount-proc /nix/store/5p3n24in6is3yzpvp7d29vzpbrh88fgb-systemd-wrapper.sh 
> /nix/store/5p3n24in6is3yzpvp7d29vzpbrh88fgb-systemd-wrapper.sh: line 2: mount: command not found

**Comment by nzbr** [comment] 2022-04-08 07:12
It is on my installation though (as before, it's a fresh install from the exact same tar. All the nix stores have the same hashes too) - but it's in `/run/wrappers/bin`. I'm currently trying to figure out, where that comes from

**Comment by dingdang66686** [comment] 2022-04-08 07:13
> That is the systemd PID from outside the namespace

Ok, but systemd is not running. so the result is 
> nsenter: cannot open /proc/196/ns/pid: No such file or directory

**Comment by nzbr** [comment] 2022-04-08 07:24
Does `/run/wrappers/bin/mount` exist on your installation?

**Comment by dingdang66686** [comment] 2022-04-08 07:25
Yes

**Comment by dingdang66686** [comment] 2022-04-08 07:30
I try to run systemd manually but got this:
> [root@nixos:~]# unshare --mount-proc /run/current-system/systemd/lib/systemd/systemd
> Explicit --user argument required to run as user manager.

**Comment by nzbr** [comment] 2022-04-08 07:31
Maybe adding `/run/wrappers/bin` to PATH before the unshare command helps?

Also: Can you give me the output of `uname -a` as well as your Windows version/build number (from `winver.exe`)

Mine are:
`Linux hurricane 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux`  
`Version 21H2 (Build 22000.593)`

**Comment by nzbr** [comment] 2022-04-08 07:32
you are missing the `-fp` options on the unshare command (those make systemd run as PID 1)

**Comment by dingdang66686** [comment] 2022-04-08 07:32
But if I fork it, how can I get logs?

**Comment by dingdang66686** [comment] 2022-04-08 07:33
WSL Version: 2
Locale: zh_CN
Release Install Date: Thu Apr  7 17:57:53 CST 2022
Branch: ni_release
Build: 22593
Full Build: 22593.1.amd64fre.ni_release.220402-1100
Display Scaling: 1.5
Windows Theme: light
Windows Uptime: 0d 5h 49m
WSL Uptime: 0d 0h 52m
WSL Release: Ubuntu Jammy Jellyfish (development branch)
WSL Kernel: Linux 5.10.102.1-microsoft-standard-WSL2
Packages Count: 1754

**Comment by nzbr** [comment] 2022-04-08 07:35
I'd be really grateful if you figured that out, because I have not figured out how to do that...
For most cases it's sufficient to get the logs through journalctl, but that wont' work if systemd does not start

**Comment by nzbr** [comment] 2022-04-08 07:37
Thanks, I'm installing a VM with your Windows build now, to see if that causes the problem

**Comment by dingdang66686** [comment] 2022-04-08 07:38
Maybe the locale? I'm changing my system to English.

**Comment by nzbr** [comment] 2022-04-08 07:39
It's worth a shot I guess

**Comment by nzbr** [comment] 2022-04-08 07:46
Which SKU are you using Home/Home China/Pro? (So that I can grab the right ISO)

**Comment by dingdang66686** [comment] 2022-04-08 07:47
Nothing different. I just reimported the distro and start it but with no luck. 😅

**Comment by dingdang66686** [comment] 2022-04-08 07:50
PRO edition

**Comment by dingdang66686** [comment] 2022-04-08 08:10
Well, I think I've found out the reason. I've added a kernel command line for enabling cgroup v2. After removing it, the issue was resolved. Sorry for your time.
> [wsl2]
> kernelCommandLine = bonding.max_bonds=0 dummy.numdummies=0 fb_tunnels=none ~~systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=named~~

**Comment by nzbr** [comment] 2022-04-08 08:15
Oh well xD. Glad that you could fix it! Is cgroups v2 going to replace v1? If yes, syschdemd should probably be patched to support v2 as well

**Comment by dingdang66686** [comment] 2022-04-08 08:19
Podman requires cgroup v2. So I enabled it.

**Comment by nzbr** [comment] 2022-04-08 08:20
So it _should_ be fixed

**Comment by dingdang66686** [comment] 2022-04-08 09:03
BTW, by adding a option to .wslconfig you can open a debug console for wsl.
> debugConsole = true

**Comment by Jumail** [comment] 2022-09-06 10:16
For those who have this issue, try shutting down your other distros with `wsl --shutdown`
after that you can now run `wsl -d NixOS`

This seems to work for me.

**Comment by burntcarrot** [comment] 2022-09-12 14:35
@Jumail thanks, this worked!

@nzbr Just to point out that this occurs on version `22.05` only, I wasn't able to replicate this on `21.11`. Maybe a small note on the README would help people out with this issue?

**Comment by r351574nc3** [comment] 2022-09-12 22:19
I am running into this. There are no other distros installed, so `wsl --shutdown` didn't help. It's just stuck trying to start `systemd`

**Comment by burntcarrot** [comment] 2022-09-13 04:51
@r351574nc3 I had the same issue. Downgraded to `21.11` with the [fixed version](https://github.com/nix-community/NixOS-WSL/releases/tag/21.11-d89f18a1), and `systemd` didn't get stuck.

On `22.05`, it is a problem. You could try restarting the `LxssManager` service from the Task Manager.

**Comment by scottstephens** [comment] 2022-10-07 20:36
I had the same issue (systemd hanging on first boot). It was my first wsl distro installation. `wsl --shutdown` did not help, but restarting my computer fixed it.

**Comment by burkaman** [comment] 2022-11-01 18:01
I had the same issue with the first boot hanging at `Starting systemd...`. Restarting WSL did not help, I didn't try restarting my computer. I installed the fixed 21.11 version and then upgraded following the instructions in the 22.05 release, and that seems to have worked.

Here's the output from `wsl -v`:
```
WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.755
```

**Comment by giang-nghg** [comment] 2022-11-08 21:33
@nzbr Curiously, if I clone the repo fresh and build it, then import it, then systemd starts normally. Seems like only pre-built releases are affected.

**Comment by K900** [comment] 2023-09-30 05:40
Is this still an issue on recent WSL versions? cgroupv2 should be default now.

**Comment by SuperSandro2000** [comment] 2023-10-12 09:23
I don't think so, closing

**Closed by SuperSandro2000** 2023-10-12 09:23 UTC
Labels: bug
